const { Plugin, ItemView, Modal, Notice, TFile, SuggestModal, normalizePath } = require("obsidian");

const SCHEMA_FOLDER = "data/schema";
const LEGACY_SCHEMA_FOLDER = "schemas";
const DATA_FOLDER = "data/record";
const CONFIG_FOLDER = "data/config";
const ROOT_CONFIG_FOLDER = "config";
const ASSET_FOLDER = "data/assets";
const BASE_FOLDER = "data";
const BASE_VIEW_FOLDER = "data/base";
const PLACEHOLDER_PREFIX = "_placeholder.";
const LIST_FOLDER = "data/config";
const TABLE_FOLDER = "data/tables";
const ASSET_CONFIG_FOLDER = "assets/config";
const SCHEMA_MAPPING_FILE = "data/config/schema-mappings.md";
const LEGACY_MAPPING_FILE = "config/schema-mappings.md";
const SAMPLE_DATABASE = "AssetDatabase";
const VIEW_TYPE_SCHEMA_SYNC = "schema-sync-dashboard";
const IDENTITY_FIELDS = new Set(["id", "name"]);
// `attachment` is a string carrying a [[wikilink]] to a media file. Asset
// Renamer builds its property dropdown from a note's frontmatter keys, so an
// attachment field becomes editable there as soon as the key exists.
const FIELD_TYPES = ["string", "number", "boolean", "array", "object", "attachment"];
// Unbound fields are documentation only: shown in the definition editor and the
// schema note, but never pushed into records, config lists, base views or DBML.
const isBound = (definition) => definition.bind !== false;
const storageType = (type) => (type === "attachment" ? "string" : type);

/* ------------------------------------------------------------------------ *
 * Pure generators. No Obsidian API, no I/O, no `this`.
 * Everything between this banner and the next one is unit-testable under
 * plain node, which is the only way the output formats can be verified
 * without launching Obsidian.
 * ------------------------------------------------------------------------ */

function emptyValue(type) {
  if (type === "number") return 0;
  if (type === "boolean") return false;
  if (type === "array") return [];
  if (type === "object") return {};
  return "";
}

function reorderFields(fields, fromName, toName) {
  const names = Object.keys(fields);
  const from = names.indexOf(fromName);
  const to = names.indexOf(toName);
  if (from < 0 || to < 0 || from === to) return { ...fields };
  names.splice(to, 0, ...names.splice(from, 1));
  return Object.fromEntries(names.map((name) => [name, fields[name]]));
}

// Renames a key while holding its position, so reordering and renaming stay
// independent operations.
function renameField(fields, oldName, newName) {
  return Object.fromEntries(Object.entries(fields).map(([name, definition]) => [name === oldName ? newName : name, definition]));
}

function isEmptyValue(value) {
  if (typeof value === "string") return value.trim() === "";
  if (Array.isArray(value)) return value.length === 0;
  if (value && typeof value === "object") return Object.keys(value).length === 0;
  return false;
}

function yamlValue(value) {
  if (typeof value === "string") return JSON.stringify(value);
  if (value === undefined) return "null";
  return JSON.stringify(value);
}

function frontmatterText(values) {
  return Object.entries(values).map(([name, value]) => `${name}: ${yamlValue(value)}`).join("\n");
}

function pluralize(word) {
  if (!word) return "";
  if (/[^aeiou]y$/i.test(word)) return `${word.slice(0, -1)}ies`;
  if (/(s|x|z|ch|sh)$/i.test(word)) return `${word}es`;
  return `${word}s`;
}

function recordValuesFor(schemaName, fields) {
  const values = { implements: schemaName };
  for (const [name, definition] of Object.entries(fields)) {
    if (!isBound(definition)) continue;
    values[name] = definition.hasDefault ? definition.defaultValue : emptyValue(definition.type);
  }
  return values;
}

function renderRecordFrontmatter(schemaName, fields) {
  return frontmatterText(recordValuesFor(schemaName, fields));
}

// Obsidian Bases YAML. Shape mirrors the vault's own working config/config.base:
// filters nested inside the view, plain-scalar expressions, trailing `sort: []`.
function renderBaseYaml(schemaName, fields, recordFolder) {
  const columns = ["file.name", ...Object.entries(fields).filter(([, d]) => isBound(d)).map(([name]) => name)];
  return [
    "# Generated by Schema Sync. Edits are overwritten on the next sync.",
    "views:",
    "  - type: table",
    `    name: ${schemaName}`,
    "    filters:",
    "      and:",
    `        - file.inFolder("${recordFolder}")`,
    "    order:",
    ...columns.map((column) => `      - ${column}`),
    "    sort: []",
    "",
  ].join("\n");
}

// Reads back the first column of a .config.md table, dropping the header and
// separator rows, so regeneration can union rather than replace.
function parseConfigValues(raw) {
  const cells = [];
  for (const line of String(raw || "").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed.startsWith("|") || !trimmed.endsWith("|")) continue;
    cells.push(trimmed.slice(1, -1).split("|")[0].trim());
  }
  if (cells.length >= 2 && /^:?-{2,}:?$/.test(cells[1])) cells.splice(0, 2);
  return cells
    .map((cell) => {
      const link = cell.match(/^\[\[([^\]|]+?)(?:\|[^\]]*)?\]\]$/);
      return (link ? link[1] : cell).trim();
    })
    .filter(Boolean);
}

function renderConfigNote(attributeName, sources, values, existingValues) {
  const merged = [...new Set([...(existingValues || []), ...(values || [])]
    .map((value) => String(value).trim())
    .filter(Boolean))].sort((a, b) => a.localeCompare(b));
  return [
    "---",
    `configFor: [${(sources || []).join(", ")}]`,
    "---",
    "",
    `# ${pluralize(attributeName)}`,
    "",
    `Unique \`${attributeName}\` values available for selection. Generated by Schema Sync; rows added by hand are preserved across syncs.`,
    "",
    `| ${attributeName} | Notes |`,
    "| --- | --- |",
    ...merged.map((value) => `| [[${value}]] |  |`),
    "",
  ].join("\n");
}

function renderFieldReference(fields) {
  const rows = Object.entries(fields).map(([name, field]) =>
    `| ${name} | ${field.type} | ${field.hasDefault ? yamlValue(field.defaultValue) : "-"} | ${field.required ? "yes" : "no"} | ${isBound(field) ? "yes" : "no"} |`);
  return `## Field Reference\n\n| Field | Type | Default | Required | Bound |\n| --- | --- | --- | --- | --- |\n${rows.join("\n")}\n`;
}

function renderSchemaFields(fields) {
  return Object.entries(fields).map(([fieldName, definition]) => {
    const lines = [`  - ${fieldName}:`, `      type: ${definition.type}`];
    if (definition.required) lines.push("      required: true");
    if (definition.hasDefault) lines.push(`      default: ${yamlValue(definition.defaultValue)}`);
    if (definition.relation?.target) lines.push(`      relation: ${definition.relation.target}`);
    // Written only when false, so existing schema notes stay byte-identical.
    if (!isBound(definition)) lines.push("      bind: false");
    return lines.join("\n");
  }).join("\n");
}

function defaultSchemaBody(name, sourcePath) {
  const intro = sourcePath ? `Source implementation: [[${String(sourcePath).replace(/\.md$/i, "")}]]\n\n` : "";
  return `${intro}Defines the base fields for any ${name} note.`;
}

// Strips frontmatter, the title heading, and the generated Field Reference,
// leaving the author's prose so a rewrite does not destroy it.
function schemaBodyOf(raw) {
  return String(raw || "")
    .replace(/^---[\s\S]*?\n---\n?/, "")
    .replace(/\n?##\s+Field Reference[\s\S]*$/i, "")
    .replace(/^#\s+.*$/m, "")
    .trim();
}

function renderSchemaNote(name, fields, sourcePath, body) {
  const frontmatter = ["---", `schema: ${name}`];
  if (sourcePath) frontmatter.push(`schemaSource: ${sourcePath}`);
  frontmatter.push("fields:");
  const fieldBlock = renderSchemaFields(fields);
  if (fieldBlock) frontmatter.push(fieldBlock);
  frontmatter.push("---");
  const prose = (body && body.trim()) || defaultSchemaBody(name, sourcePath);
  return `${frontmatter.join("\n")}\n\n# ${name} Schema\n\n${prose}\n\n${renderFieldReference(fields)}`;
}

function dbmlColumnType(type) {
  return type === "number" ? "int" : type === "boolean" ? "boolean" : "varchar";
}

function dbmlRefTarget(targetFields) {
  if (!targetFields) return undefined;
  if (targetFields.id) return "id";
  if (targetFields.name) return "name";
  return Object.keys(targetFields)[0];
}

function renderDbml(schemas) {
  const entries = typeof schemas?.entries === "function" ? [...schemas.entries()] : Object.entries(schemas || {});
  const lookup = new Map(entries);
  const tables = entries.map(([name, fields]) => {
    const columns = Object.entries(fields)
      .filter(([, definition]) => isBound(definition))
      .map(([fieldName, definition]) => `  ${fieldName} ${dbmlColumnType(definition.type)}${definition.required ? " [not null]" : ""}`)
      .join("\n");
    return `Table ${name} {\n${columns}\n}`;
  });
  const relations = [];
  for (const [name, fields] of entries) {
    for (const [fieldName, definition] of Object.entries(fields)) {
      if (!isBound(definition)) continue;
      const target = definition.relation?.target;
      if (!target || !lookup.has(target)) continue;
      const key = dbmlRefTarget(lookup.get(target));
      if (key) relations.push(`Ref: ${name}.${fieldName} > ${target}.${key}`);
    }
  }
  return `${tables.join("\n\n")}\n${relations.join("\n")}`;
}

function renderErdNote(databaseName, schemas) {
  return `# ${databaseName} Database\n\nGenerated DBML base view for the DBML Visualizer plugin.\n\n\`\`\`dbml title="${databaseName} ERD"\n${renderDbml(schemas)}\n\`\`\`\n`;
}

/* --------------------------- end pure generators -------------------------- */

class SchemaInputModal extends Modal {
  constructor(app, title, placeholder, defaultValue, onSubmit) {
    super(app);
    this.title = title;
    this.placeholder = placeholder;
    this.defaultValue = defaultValue;
    this.onSubmit = onSubmit;
  }

  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.title });
    const input = contentEl.createEl("input", { type: "text", placeholder: this.placeholder });
    input.value = this.defaultValue || "";
    input.style.width = "100%";
    const submit = contentEl.createEl("button", { text: "Continue" });
    submit.addEventListener("click", () => {
      const value = input.value.trim();
      this.close();
      if (value) {
        Promise.resolve(this.onSubmit(value)).catch((error) => {
          new Notice(`Schema action failed: ${error instanceof Error ? error.message : String(error)}`);
        });
      }
    });
    input.addEventListener("keydown", (event) => {
      if (event.key === "Enter") submit.click();
    });
    window.setTimeout(() => input.focus(), 0);
  }

  onClose() { this.contentEl.empty(); }
}

class ConfirmDeleteModal extends Modal {
  constructor(app, title, body, confirmLabel, onResolve) {
    super(app);
    this.title = title;
    this.body = body;
    this.confirmLabel = confirmLabel;
    this.onResolve = onResolve;
    this.answered = false;
  }

  resolve(confirmed, remember) {
    if (this.answered) return;
    this.answered = true;
    this.onResolve({ confirmed, remember });
    this.close();
  }

  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.title });
    contentEl.createEl("p", { text: this.body });
    const remember = contentEl.createEl("label", { cls: "schema-sync-modal-remember" });
    const checkbox = remember.createEl("input", { type: "checkbox" });
    remember.appendText(" Don't ask again this session");
    const actions = contentEl.createDiv({ cls: "schema-sync-modal-actions" });
    actions.createEl("button", { text: "Cancel" }).addEventListener("click", () => this.resolve(false, false));
    const confirm = actions.createEl("button", { text: this.confirmLabel, cls: "mod-warning" });
    confirm.addEventListener("click", () => this.resolve(true, checkbox.checked));
    confirm.focus();
  }

  onClose() {
    this.contentEl.empty();
    this.resolve(false, false);
  }
}

class SchemaSyncView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.selectedSchema = null;
    this.selectedEntity = null;
  }

  getViewType() { return VIEW_TYPE_SCHEMA_SYNC; }
  getDisplayText() { return "Schema Sync"; }
  getIcon() { return "workflow"; }

  async onOpen() { this.render(); }
  async onClose() { this.contentEl.empty(); }

  render() {
    const schemas = [...this.plugin.schemas.entries()];
    if (!this.selectedSchema || !this.plugin.schemas.has(this.selectedSchema)) this.selectedSchema = schemas[0]?.[0];
    const schemaName = this.selectedSchema;
    const fields = this.plugin.schemas.get(schemaName) || {};
    // Templates are listed too. A schema whose only file is _placeholder.X used
    // to report "No mapped entities", which read as nothing being mapped at all.
    const entities = this.plugin.dataFiles().filter((file) => this.plugin.app.metadataCache.getFileCache(file)?.frontmatter?.implements === schemaName);
    if (!this.selectedEntity || !entities.some((file) => file.path === this.selectedEntity.path)) this.selectedEntity = entities[0];
    const selectedFrontmatter = this.selectedEntity ? this.plugin.app.metadataCache.getFileCache(this.selectedEntity)?.frontmatter || {} : {};
    const fieldRows = Object.entries(fields).map(([name, definition]) => { const value = Object.prototype.hasOwnProperty.call(selectedFrontmatter, name) ? selectedFrontmatter[name] : definition.hasDefault ? definition.defaultValue : "—"; return `<div class="schema-sync-property"><span><b>${name}</b><small>${definition.type}${definition.required ? " · required" : ""}</small></span><code>${this.plugin.yamlValue(value)}</code></div>`; }).join("");
    this.contentEl.empty();
    this.contentEl.addClass("schema-sync-view");
        this.contentEl.innerHTML = `<div class="schema-sync-head"><div><small>SCHEMA SYNC / VAULT ARCHITECTURE</small><h1>Schema dashboard</h1></div><button data-action="sync">Sync schema system</button></div><div class="schema-sync-grid"><section><small class="schema-sync-label">01 / Registry</small><h2>Manage schemas</h2><div class="schema-sync-list">${schemas.map(([name, schemaFields]) => `<button class="schema-sync-schema ${name === schemaName ? "is-active" : ""}" data-schema="${name}"><span>${name.slice(0, 1)}</span><b>${name}</b><small>${Object.keys(schemaFields).length} properties</small></button>`).join("")}</div></section><section><small class="schema-sync-label">02 / Relation</small><h2>Entity mapping</h2><div class="schema-sync-count"><b>${entities.length}</b><small>mapped entities</small></div><div class="schema-sync-entities">${entities.map((file) => { const fm = this.plugin.app.metadataCache.getFileCache(file)?.frontmatter || {}; const isTemplate = file.basename.startsWith(PLACEHOLDER_PREFIX); const missing = Object.keys(fields).filter((name) => !(name in fm) && fields[name].required).length; const badge = isTemplate ? "template" : missing ? `${missing} issue` : "In sync"; return `<button class="schema-sync-entity ${file.path === this.selectedEntity?.path ? "is-active" : ""}" data-entity="${file.path}"><b>${file.basename}</b><small>${file.path}</small><em class="${isTemplate ? "is-template" : missing ? "is-warning" : ""}">${badge}</em></button>`; }).join("") || "<p class=\"schema-sync-empty\">No mapped entities.</p>"}</div></section><section><small class="schema-sync-label">03 / Resolved entity</small><h2>${this.selectedEntity?.basename || "Select an entity"}</h2><small class="schema-sync-path">${this.selectedEntity?.path || "Choose a note from the mapping panel"}</small><div class="schema-sync-inherits">↳ Inherits from <b>${schemaName || "—"}</b></div><div class="schema-sync-properties">${this.selectedEntity ? fieldRows : "<p class=\"schema-sync-empty\">No entity selected.</p>"}</div></section></div>`;
        const grid = this.contentEl.querySelector(".schema-sync-grid");
        const sections = grid ? [...grid.children] : [];
        if (grid && sections.length === 3) {
          grid.append(sections[0], sections[2], sections[1]);
        }
        const editorPanel = this.contentEl.querySelector(".schema-sync-grid > section:nth-child(2)");
        if (editorPanel) {
          editorPanel.innerHTML = `<small class="schema-sync-label">02 / Definition</small><h2>Edit ${schemaName || "schema"}</h2><p class="schema-sync-editor-help">Click ✎ to edit a row. Enter saves, Escape cancels. Drag ⠿ to reorder. Unbound fields stay documented here but are not written to records, config lists, base views or the ERD.</p><div class="schema-sync-field-editor">${Object.entries(fields).map(([name, definition]) => `<div class="schema-sync-field-row" data-schema-row="${name}"><span class="schema-sync-drag" draggable="true" title="Drag to reorder">⠿</span><input data-field-name value="${name}" aria-label="Field name" /><select data-field-type aria-label="Field type">${FIELD_TYPES.map((type) => `<option value="${type}" ${definition.type === type ? "selected" : ""}>${type}</option>`).join("")}</select><input data-field-default value="${this.plugin.editorValue(definition.hasDefault ? definition.defaultValue : "")}" placeholder="default" aria-label="Default value" /><select data-field-relation aria-label="Foreign key target"><option value="">no foreign key</option>${schemas.map(([target]) => `<option value="${target}" ${definition.relation?.target === target ? "selected" : ""}>→ ${target}</option>`).join("")}</select><select data-field-bind aria-label="Bind to data" title="Bound fields are written to records, config lists, base views and the ERD"><option value="yes" ${definition.bind !== false ? "selected" : ""}>bind: yes</option><option value="no" ${definition.bind === false ? "selected" : ""}>bind: no</option></select><label><input data-field-required type="checkbox" ${definition.required ? "checked" : ""} /> required</label><button data-delete-field="${name}" title="Remove field">×</button></div>`).join("") || "<p class=\"schema-sync-empty\">No fields defined.</p>"}</div>`;
          const definitionHeader = document.createElement("div");
          definitionHeader.className = "schema-sync-definition-header";
          const definitionTitle = editorPanel.querySelector("h2");
          if (definitionTitle) {
            definitionTitle.parentElement?.insertBefore(definitionHeader, definitionTitle);
            definitionHeader.appendChild(definitionTitle);
          }
          const addFieldButton = document.createElement("button");
          addFieldButton.className = "schema-sync-add-field";
          addFieldButton.textContent = "+ Add field";
          addFieldButton.dataset.action = "add-definition-field";
          definitionHeader.appendChild(addFieldButton);
          const lockRow = (row) => {
            row.querySelectorAll("input, select").forEach((control) => { control.disabled = true; });
            row.classList.remove("is-editing");
          };
          // Snapshot on unlock so Escape has something exact to restore to.
          const snapshotRow = (row) => [...row.querySelectorAll("input, select")].map((control) => (control.type === "checkbox" ? control.checked : control.value));
          const restoreRow = (row, snapshot) => {
            [...row.querySelectorAll("input, select")].forEach((control, index) => {
              if (control.type === "checkbox") control.checked = snapshot[index];
              else control.value = snapshot[index];
            });
          };
          editorPanel.querySelectorAll("[data-schema-row]").forEach((row) => {
            lockRow(row);
            const editButton = document.createElement("button");
            editButton.className = "schema-sync-row-action";
            editButton.dataset.editField = row.dataset.schemaRow;
            editButton.title = `Edit ${row.dataset.schemaRow}`;
            editButton.textContent = "✎";
            row.insertBefore(editButton, row.querySelector("[data-delete-field]"));
          });
          editorPanel.querySelectorAll("[data-delete-field]").forEach((button) => button.addEventListener("click", () => void this.plugin.deleteSchemaField(schemaName, button.dataset.deleteField)));
          editorPanel.querySelectorAll("[data-edit-field]").forEach((button) => button.addEventListener("click", () => {
            const row = button.closest("[data-schema-row]");
            // Guard against a second click stacking another set of key handlers
            // on the same row.
            if (!row || row.classList.contains("is-editing")) return;
            row.querySelectorAll("input, select").forEach((control) => { control.disabled = false; });
            row.classList.add("is-editing");
            const snapshot = snapshotRow(row);
            row.querySelectorAll("input, select").forEach((control) => {
              control.addEventListener("keydown", (event) => {
                // Escape must abandon the edit outright. Relying on the browser
                // to revert an input is not dependable inside Electron.
                if (event.key === "Escape") {
                  event.preventDefault();
                  event.stopPropagation();
                  restoreRow(row, snapshot);
                  lockRow(row);
                } else if (event.key === "Enter") {
                  event.preventDefault();
                  control.blur();
                }
              });
            });
          }));
          editorPanel.querySelector("[data-action=add-definition-field]")?.addEventListener("click", () => void this.plugin.updateSchema(schemaName));
          editorPanel.querySelectorAll("[data-schema-row] input, [data-schema-row] select").forEach((control) => control.addEventListener("change", () => {
            if (control.disabled) return;
            void this.plugin.saveSchemaFromDashboard(schemaName, editorPanel);
          }));
          let draggedRow = null;
          editorPanel.querySelectorAll(".schema-sync-drag").forEach((handle) => {
            const row = handle.closest("[data-schema-row]");
            handle.addEventListener("dragstart", (event) => {
              draggedRow = row;
              row.classList.add("is-dragging");
              event.dataTransfer.effectAllowed = "move";
              // Firefox and Electron both refuse to start a drag without data.
              event.dataTransfer.setData("text/plain", row.dataset.schemaRow);
            });
            handle.addEventListener("dragend", () => {
              row.classList.remove("is-dragging");
              editorPanel.querySelectorAll(".is-drop-target").forEach((el) => el.classList.remove("is-drop-target"));
              draggedRow = null;
            });
          });
          editorPanel.querySelectorAll("[data-schema-row]").forEach((row) => {
            row.addEventListener("dragover", (event) => {
              if (!draggedRow || draggedRow === row) return;
              event.preventDefault();
              event.dataTransfer.dropEffect = "move";
              row.classList.add("is-drop-target");
            });
            row.addEventListener("dragleave", () => row.classList.remove("is-drop-target"));
            row.addEventListener("drop", (event) => {
              event.preventDefault();
              row.classList.remove("is-drop-target");
              if (!draggedRow || draggedRow === row) return;
              void this.plugin.reorderSchemaFields(schemaName, draggedRow.dataset.schemaRow, row.dataset.schemaRow);
            });
          });
        }
        const relationLabel = this.contentEl.querySelector(".schema-sync-grid > section:nth-child(3) .schema-sync-label");
        if (relationLabel) relationLabel.textContent = "03 / Relation";
        const registry = this.contentEl.querySelector(".schema-sync-grid > section:nth-child(1)");
        if (registry) {
          const registryHeader = document.createElement("div");
          registryHeader.className = "schema-sync-registry-header";
          const registryTitle = registry.querySelector("h2");
          if (registryTitle) {
            registryTitle.parentElement?.insertBefore(registryHeader, registryTitle);
            registryHeader.appendChild(registryTitle);
          }
          const newButton = document.createElement("button");
          newButton.className = "schema-sync-new-button";
          newButton.textContent = "+ New schema";
          newButton.dataset.action = "create-schema-registry";
          registryHeader.appendChild(newButton);
          registry.querySelectorAll(".schema-sync-schema").forEach((row) => {
            const schemaNameForRow = row.dataset.schema;
            const wrapper = document.createElement("div");
            wrapper.className = "schema-sync-schema-row";
            const selectButton = document.createElement("button");
            selectButton.className = row.className;
            selectButton.dataset.schema = schemaNameForRow;
            selectButton.innerHTML = row.innerHTML;
            const duplicateButton = document.createElement("button");
            duplicateButton.className = "schema-sync-row-action";
            duplicateButton.dataset.duplicateSchema = schemaNameForRow;
            duplicateButton.title = `Duplicate ${schemaNameForRow}`;
            duplicateButton.textContent = "⧉";
            const deleteButton = document.createElement("button");
            deleteButton.className = "schema-sync-row-action schema-sync-row-delete";
            deleteButton.dataset.deleteSchema = schemaNameForRow;
            deleteButton.title = `Delete ${schemaNameForRow}`;
            deleteButton.textContent = "×";
            wrapper.append(selectButton, duplicateButton, deleteButton);
            row.replaceWith(wrapper);
          });
        }
        const actionBar = document.createElement("div");
        actionBar.className = "schema-sync-action-bar";
        [
          ["Add / update field", "update-schema"],
          ["Delete schema", "delete-schema"],
          ["Bind fields", "bind-fields"],
          ["Unbind fields", "unbind-fields"],
          ["Reattach from file", "reattach-schema"],
          ["Open ERD base", "open-base"],
        ].forEach(([label, action]) => {
          const button = document.createElement("button");
          button.textContent = label;
          button.dataset.action = action;
          actionBar.appendChild(button);
        });
        this.contentEl.querySelector(".schema-sync-head")?.appendChild(actionBar);
        const mapping = this.plugin.currentMappings()[schemaName];
        const mappingNote = document.createElement("small");
        mappingNote.className = "schema-sync-mapping-note";
        mappingNote.textContent = mapping ? `Bound to ${mapping.target}` : "No target config binding";
        this.contentEl.querySelector(".schema-sync-inherits")?.after(mappingNote);
        const relationPanel = this.contentEl.querySelector(".schema-sync-grid > section:nth-child(3)");
        if (relationPanel && schemaName) {
          // Each entity row gets duplicate and asset-renamer actions, mirroring
          // the 01/Registry row layout.
          relationPanel.querySelectorAll(".schema-sync-entity").forEach((entityRow) => {
            const entityPath = entityRow.dataset.entity;
            const wrapper = document.createElement("div");
            wrapper.className = "schema-sync-entity-row";
            const openButton = document.createElement("button");
            openButton.className = entityRow.className;
            openButton.dataset.entity = entityPath;
            openButton.innerHTML = entityRow.innerHTML;
            const duplicateButton = document.createElement("button");
            duplicateButton.className = "schema-sync-row-action";
            duplicateButton.dataset.duplicateEntity = entityPath;
            duplicateButton.title = "Duplicate this record";
            duplicateButton.textContent = "⧉";
            const assetButton = document.createElement("button");
            assetButton.className = "schema-sync-row-action";
            assetButton.dataset.assetEntity = entityPath;
            assetButton.title = "Open Asset Renamer for this record";
            assetButton.textContent = "🖼";
            const deleteButton = document.createElement("button");
            deleteButton.className = "schema-sync-row-action schema-sync-row-delete";
            deleteButton.dataset.deleteEntity = entityPath;
            deleteButton.title = "Delete this record";
            deleteButton.textContent = "×";
            wrapper.append(openButton, duplicateButton, assetButton, deleteButton);
            entityRow.replaceWith(wrapper);
          });
          // Always offered, not only when the schema has no records yet.
          const implementButton = document.createElement("button");
          implementButton.className = "schema-sync-implement";
          implementButton.textContent = `+ New ${schemaName} record`;
          implementButton.dataset.action = "implement-entity";
          this.contentEl.querySelector(".schema-sync-entities")?.appendChild(implementButton);
        }
        this.contentEl.querySelectorAll("[data-duplicate-entity]").forEach((button) => button.addEventListener("click", (event) => { event.stopPropagation(); void this.plugin.duplicateRecord(button.dataset.duplicateEntity); }));
        this.contentEl.querySelectorAll("[data-asset-entity]").forEach((button) => button.addEventListener("click", (event) => { event.stopPropagation(); void this.plugin.openAssetRenamer(button.dataset.assetEntity); }));
        this.contentEl.querySelectorAll("[data-delete-entity]").forEach((button) => button.addEventListener("click", (event) => { event.stopPropagation(); void this.plugin.deleteRecord(button.dataset.deleteEntity); }));
    this.contentEl.querySelectorAll("[data-schema]").forEach((el) => el.addEventListener("click", () => { this.selectedSchema = el.dataset.schema; this.selectedEntity = null; this.render(); }));
    this.contentEl.querySelectorAll("[data-entity]").forEach((el) => el.addEventListener("click", () => {
      const file = this.plugin.app.vault.getAbstractFileByPath(el.dataset.entity);
      if (file instanceof TFile) void this.plugin.app.workspace.getLeaf(true).openFile(file);
    }));
    this.contentEl.querySelector("[data-action=sync]")?.addEventListener("click", () => void this.plugin.syncSystem(true));
    this.contentEl.querySelector("[data-action=open-base]")?.addEventListener("click", () => void this.plugin.openBaseNote(schemaName));
        this.contentEl.querySelector("[data-action=create-schema]")?.addEventListener("click", () => void this.plugin.createSchema());
        this.contentEl.querySelector("[data-action=update-schema]")?.addEventListener("click", () => void this.plugin.updateSchema(schemaName));
        this.contentEl.querySelector("[data-action=delete-schema]")?.addEventListener("click", () => void this.plugin.deleteSchema(schemaName));
        this.contentEl.querySelector("[data-action=bind-fields]")?.addEventListener("click", () => void this.plugin.bindFields(schemaName));
        this.contentEl.querySelector("[data-action=unbind-fields]")?.addEventListener("click", () => void this.plugin.unbindFields(schemaName));
        this.contentEl.querySelector("[data-action=reattach-schema]")?.addEventListener("click", () => void this.plugin.reattachSchema());
        this.contentEl.querySelector("[data-action=implement-entity]")?.addEventListener("click", () => void this.plugin.implementEntity(schemaName));
        this.contentEl.querySelector("[data-action=create-schema-registry]")?.addEventListener("click", () => void this.plugin.createSchema());
        this.contentEl.querySelectorAll("[data-duplicate-schema]").forEach((button) => button.addEventListener("click", (event) => { event.stopPropagation(); void this.plugin.duplicateSchema(button.dataset.duplicateSchema); }));
        this.contentEl.querySelectorAll("[data-delete-schema]").forEach((button) => button.addEventListener("click", (event) => { event.stopPropagation(); void this.plugin.deleteSchema(button.dataset.deleteSchema); }));
  }
}

class SchemaSyncPlugin extends Plugin {
  pending = new Map();
  patching = new Set();
  schemas = new Map();
  schemaValidationTimeout = null;
  schemaReloadTimeout = null;
  // Schema notes the user is editing by hand. While a path is in here the sync
  // will not rewrite it; edits flow the other way, from note to registry.
  safetyOff = new Set();
  // "Don't ask again" for field deletion, deliberately session-scoped so it
  // never persists across a restart.
  skipDeleteConfirm = false;
  skipRecordDeleteConfirm = false;
  // Schema notes edited while focused. Their sync is held until focus leaves the
  // file, so typing is never interrupted by a vault-wide rewrite.
  pendingSchemaEdits = new Set();
  schemaPreviewTimeout = null;

  async onload() {
    this.registerView(VIEW_TYPE_SCHEMA_SYNC, (leaf) => new SchemaSyncView(leaf, this));
    this.addRibbonIcon("workflow", "Open schema dashboard", () => {
      void this.openDashboard();
    });
    this.statusBar = this.addStatusBarItem();
    this.statusBar.setText("Schema Sync: loading");

    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        if (!this.isSchemaPath(file.path)) return this.scheduleValidation(file);
        // While the note is the focused file it belongs to the user. Hold the
        // sync, and only refresh the dashboard so edits are still visible.
        if (this.app.workspace.getActiveFile()?.path === file.path) {
          this.pendingSchemaEdits.add(file.path);
          this.scheduleSchemaPreview();
          return;
        }
        this.scheduleSchemaValidation();
      })
    );
    this.registerEvent(this.app.vault.on("modify", (file) => {
      if (file instanceof TFile && (file.path.startsWith(`${ASSET_CONFIG_FOLDER}/`) || file.path.startsWith(`${CONFIG_FOLDER}/`) || file.path.startsWith(`${ROOT_CONFIG_FOLDER}/`)) && file.path !== SCHEMA_MAPPING_FILE && file.path !== LEGACY_MAPPING_FILE) {
        void this.checkImplementationColumns(file);
      }
    }));
    this.registerEvent(this.app.vault.on("create", (file) => {
      if (this.isSchemaFile(file)) return this.scheduleSchemaReload();
      // A record appearing from anywhere — the file explorer, Sync, a template —
      // has to reach the 03 panel, not just records this plugin created.
      if (file instanceof TFile && this.isRecordFile(file)) this.refreshDashboards();
    }));
    this.registerEvent(this.app.vault.on("delete", (file) => {
      if (this.isSchemaFile(file)) return this.scheduleSchemaReload();
      if (!(file instanceof TFile) || !this.isRecordFile(file)) return;
      const timeout = this.pending.get(file.path);
      if (timeout) clearTimeout(timeout);
      this.pending.delete(file.path);
      void this.forgetRecord(file.path);
      this.refreshDashboards();
    }));
    // Leaving a schema note is the signal that editing is finished. Both events
    // fire on a pane or file switch; flushing is idempotent, so both call it.
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => {
      this.releaseClosedSafetyFiles();
      void this.flushPendingSchemaEdits();
    }));
    this.registerEvent(this.app.workspace.on("file-open", () => {
      this.releaseClosedSafetyFiles();
      void this.flushPendingSchemaEdits();
    }));
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
      if (this.isSchemaPath(file.path) || this.isSchemaPath(oldPath)) this.scheduleSchemaReload();
      void this.handleTrackedRename(oldPath, file.path);
    }));
    this.addCommand({
      id: "validate-schema-notes",
      name: "Validate schema notes",
      callback: () => this.validateVault(true),
    });
    this.addCommand({
      id: "sync-schema-system",
      name: "Sync schema system",
      callback: () => this.syncSystem(true),
    });
    // Deferral already protects a note while it is focused. This is for the
    // longer case: keeping a schema note pinned open, untouched, across syncs.
    this.addCommand({
      id: "toggle-schema-safety",
      name: "Toggle schema safety for the active note",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!this.isSchemaFile(file)) return false;
        if (!checking) {
          if (this.safetyOff.delete(file.path)) new Notice(`Safety on for ${file.basename}. Sync may rewrite it again.`);
          else {
            this.safetyOff.add(file.path);
            new Notice(`Safety off for ${file.basename}. Sync will not rewrite it while it stays open.`);
          }
        }
        return true;
      },
    });
    this.addCommand({
      id: "open-schema-dashboard",
      name: "Open schema dashboard",
      callback: () => this.openDashboard(),
    });
    this.addCommand({
      id: "open-schema-erd",
      name: "Open schema ERD",
      callback: () => this.openBaseNote([...this.schemas.keys()][0]),
    });

    this.app.workspace.onLayoutReady(() => void this.initializeDatabase());
  }

  // Dashboard-only refresh: reads the registry from the metadata cache and
  // re-renders. Writes nothing, so it is safe to run against a note being typed.
  scheduleSchemaPreview() {
    if (this.schemaPreviewTimeout) clearTimeout(this.schemaPreviewTimeout);
    this.schemaPreviewTimeout = setTimeout(async () => {
      this.schemaPreviewTimeout = null;
      await this.loadSchemas();
      this.refreshDashboards();
    }, 400);
  }

  // Runs the deferred sync once the user has moved off the edited note. Files
  // still focused stay pending, so a flush triggered by an unrelated pane switch
  // does not touch the note being worked on.
  async flushPendingSchemaEdits() {
    if (this.pendingSchemaEdits.size === 0) return;
    const active = this.app.workspace.getActiveFile()?.path;
    const ready = [...this.pendingSchemaEdits].filter((path) => path !== active);
    if (ready.length === 0) return;
    for (const path of ready) this.pendingSchemaEdits.delete(path);
    await this.syncSystem(false);
    const names = ready.map((path) => path.split("/").pop().replace(/\.schema\.md$/, ""));
    new Notice(`Schema Sync: applied your edits to ${names.join(", ")}.`);
  }

  // Safety is scoped to "while the note is open", so anything no longer open in
  // a leaf is re-armed.
  releaseClosedSafetyFiles() {
    const open = new Set();
    this.app.workspace.iterateAllLeaves((leaf) => {
      const path = leaf.view?.file?.path;
      if (path) open.add(path);
    });
    for (const path of [...this.safetyOff]) if (!open.has(path)) this.safetyOff.delete(path);
  }

  async openDashboard() {
    await this.loadSchemas();
    const leaf = this.app.workspace.getLeaf(true);
    await leaf.setViewState({ type: VIEW_TYPE_SCHEMA_SYNC, active: true });
    this.app.workspace.revealLeaf(leaf);
  }

  async initializeDatabase() {
    await this.ensureFirstLaunch();
    await this.syncSystem(false);
  }

  isSchemaPath(path) {
    return path.startsWith(`${SCHEMA_FOLDER}/`) || path.startsWith(`${LEGACY_SCHEMA_FOLDER}/`);
  }

  isSchemaFile(file) {
    return file instanceof TFile && this.isSchemaPath(file.path) && file.extension === "md";
  }

  scheduleSchemaReload() {
    if (this.schemaReloadTimeout) clearTimeout(this.schemaReloadTimeout);
    this.schemaReloadTimeout = setTimeout(async () => {
      this.schemaReloadTimeout = null;
      await this.loadSchemas();
      this.refreshDashboards();
      await this.syncBaseViews();
    }, 300);
  }

  async ensureFirstLaunch() {
    const schemaFiles = this.app.vault.getMarkdownFiles().filter((file) => file.path.startsWith(`${SCHEMA_FOLDER}/`));
    if (schemaFiles.length > 0) return;
    const legacySchemas = this.app.vault.getMarkdownFiles().filter((file) => file.path.startsWith(`${LEGACY_SCHEMA_FOLDER}/`) && this.app.metadataCache.getFileCache(file)?.frontmatter?.schema);
    if (legacySchemas.length > 0) {
      if (window.confirm("Legacy schemas were found. Normalize them into data/schema using PascalCase names?")) {
        await this.ensureFolder(SCHEMA_FOLDER);
        for (const file of legacySchemas) {
          const name = this.pascalCase(this.app.metadataCache.getFileCache(file).frontmatter.schema);
          const target = normalizePath(`${SCHEMA_FOLDER}/${name}.schema.md`);
          if (!this.app.vault.getAbstractFileByPath(target)) await this.app.vault.create(target, await this.app.vault.read(file));
        }
        await this.loadSchemas();
      }
      return;
    }
    if (window.confirm("No database schema exists yet. Create a sample database with the normalized data folders?")) {
      await this.createSampleDatabase();
    }
  }

  pascalCase(value) {
    return value.split(/[^A-Za-z0-9]+/).filter(Boolean).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("") || "Database";
  }

  async createSampleDatabase() {
    const name = this.pascalCase(window.prompt("Database name", SAMPLE_DATABASE) || SAMPLE_DATABASE);
    const schemaFields = {
      name: { type: "string", required: true, hasDefault: false, defaultValue: undefined },
      description: { type: "string", required: false, hasDefault: true, defaultValue: "" },
      assetCount: { type: "number", required: false, hasDefault: true, defaultValue: 0 },
    };
    await Promise.all([SCHEMA_FOLDER, CONFIG_FOLDER, ASSET_FOLDER, BASE_VIEW_FOLDER, DATA_FOLDER].map((folder) => this.ensureFolder(folder)));
    await this.app.vault.create(normalizePath(`${SCHEMA_FOLDER}/${name}.schema.md`), renderSchemaNote(name, schemaFields, `${CONFIG_FOLDER}/${name}.config.md`));
    await this.app.vault.create(normalizePath(`${CONFIG_FOLDER}/${name}.config.md`), `# ${name} Config\n\n| name | description | assetCount |\n| --- | --- | --- |\n`);
    await this.app.vault.create(normalizePath(`${DATA_FOLDER}/${name}Instance.md`), `---\nimplements: ${name}\nname: Sample ${name}\ndescription: "Sample record"\nassetCount: 0\n---\n\n# Sample ${name}\n`);
    await this.createSampleAsset(name);
    await this.saveMappings({ [name]: { target: `${CONFIG_FOLDER}/${name}.config.md`, fields: { name: "name", description: "description", assetCount: "assetCount" } } });
    await this.loadSchemas();
    await this.syncBaseViews();
    this.refreshDashboards();
    new Notice(`${name} database created under data/.`);
  }

  async createSampleAsset(name) {
    const path = normalizePath(`${ASSET_FOLDER}/${name}Placeholder.jpg`);
    if (this.app.vault.getAbstractFileByPath(path)) return;
    const jpegBase64 = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAEFAqf/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AX//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/AX//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAY/Aqf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/IV//2gAMAwEAAgADAAAAEP/EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQMBAT8Qf//EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQIBAT8Qf//EABQQAQAAAAAAAAAAAAAAAAAAABD/2gAIAQEAAT8Qf//Z";
    const bytes = Uint8Array.from(atob(jpegBase64), (character) => character.charCodeAt(0));
    await this.app.vault.createBinary(path, bytes.buffer);
  }

  databaseName() {
    return this.pascalCase(SAMPLE_DATABASE);
  }

  async openBaseNote(schemaName) {
    const databaseName = this.pascalCase(SAMPLE_DATABASE);
    const baseFile = this.app.vault.getAbstractFileByPath(`${BASE_FOLDER}/${databaseName}.base.md`);
    if (baseFile instanceof TFile) await this.app.workspace.getLeaf(true).openFile(baseFile);
    else new Notice("No .base view exists yet. Run Sync database first.");
  }

  // The single source of truth for a schema's name. The filename wins; the
  // `schema:` property is only a fallback for legacy notes that lack the
  // `.schema` suffix. Every lookup must go through this, or the two identities
  // drift and one schema's generated content lands in another's file.
  schemaKeyFor(file) {
    if (!this.isSchemaPath(file.path)) return undefined;
    if (file.basename.endsWith(".schema")) return file.basename.slice(0, -".schema".length);
    return this.app.metadataCache.getFileCache(file)?.frontmatter?.schema;
  }

  schemaFile(schemaName) {
    return this.app.vault.getMarkdownFiles().find((file) => this.isSchemaPath(file.path) && this.schemaKeyFor(file) === schemaName);
  }

  schemaSource(schemaName) {
    const file = this.schemaFile(schemaName);
    return file ? this.app.metadataCache.getFileCache(file)?.frontmatter?.schemaSource : undefined;
  }

  refreshDashboards() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_SCHEMA_SYNC)) {
      leaf.view.render();
    }
  }

  // Rewrites an existing schema note in place, carrying its prose across. Every
  // field-editing path goes through here so none of them can wipe the body.
  async writeSchemaFile(schemaName, fields, sourceOverride) {
    const file = this.schemaFile(schemaName);
    if (!file) return null;
    const raw = await this.app.vault.read(file);
    const sourcePath = sourceOverride !== undefined ? sourceOverride : this.schemaSource(schemaName);
    await this.app.vault.modify(file, renderSchemaNote(schemaName, fields, sourcePath, schemaBodyOf(raw)));
    return file;
  }

  async writeFile(path, content) {
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (!(existing instanceof TFile)) return this.app.vault.create(path, content);
    if (await this.app.vault.read(existing) !== content) await this.app.vault.modify(existing, content);
    return existing;
  }

  parseConfigColumns(raw) {
    const table = raw.split(/\r?\n/).map((line) => line.trim()).filter((line) => line.startsWith("|") && line.endsWith("|"));
    if (table.length >= 2) {
      const columns = table[0].slice(1, -1).split("|").map((value) => value.trim()).filter(Boolean);
      const separator = table[1].slice(1, -1).split("|").every((value) => /^\s*:?-{2,}:?\s*$/.test(value));
      if (separator && columns.length > 0) return columns;
    }
    const values = raw.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
    return values.length > 0 ? ["name"] : [];
  }

  fieldsFromConfig(raw) {
    return Object.fromEntries(this.parseConfigColumns(raw).map((name) => [name.replace(/[^\w-]/g, "_") || "field", {
      type: "string",
      required: name.toLowerCase() === "name",
      hasDefault: false,
      defaultValue: undefined,
    }]));
  }

  async reattachSchema() {
    const files = this.app.vault.getMarkdownFiles().filter((file) => file.path.startsWith(`${ASSET_CONFIG_FOLDER}/`));
    const plugin = this;
    const modal = new class extends SuggestModal {
      getSuggestions(query) {
        const normalized = query.toLowerCase();
        return files.filter((file) => file.path.toLowerCase().includes(normalized));
      }
      renderSuggestion(file, element) { element.createEl("div", { text: file.path }); }
      async onChooseSuggestion(file) { await plugin.reattachFromFile(file); }
    }(this.app);
    modal.setPlaceholder("Choose an Asset Renamer config file");
    modal.open();
  }

  async reattachFromFile(file) {
    const raw = await this.app.vault.read(file);
    const schemaName = file.basename.replace(/Schema$/i, "").replace(/[^\w-]/g, "_") || "ImportedConfig";
    const fields = this.fieldsFromConfig(raw);
    const existing = this.schemaFile(schemaName);
    if (existing && !window.confirm(`Schema ${schemaName} exists. Replace its fields from ${file.path}?`)) return;
    if (existing) await this.writeSchemaFile(schemaName, fields, file.path);
    else {
      await this.ensureFolder(SCHEMA_FOLDER);
      await this.app.vault.create(normalizePath(`${SCHEMA_FOLDER}/${this.pascalCase(schemaName)}.schema.md`), renderSchemaNote(schemaName, fields, file.path));
    }
    const mappings = { ...this.currentMappings(), [schemaName]: { target: file.path, fields: Object.fromEntries(Object.keys(fields).map((name) => [name, name])) } };
    await this.saveMappings(mappings);
    await this.loadSchemas();
    this.refreshDashboards();
    new Notice(`Attached ${file.path} as schema ${schemaName}.`);
  }

  async checkImplementationColumns(file) {
    // Value lists this plugin generates live in the same folder; they are not
    // implementation targets and must not raise "define these columns" prompts.
    if (this.app.metadataCache.getFileCache(file)?.frontmatter?.configFor) return;
    const raw = await this.app.vault.read(file);
    // Checked against the raw text as well: the metadata cache lags a write, and
    // a missed guard here means a modal on every generated config file.
    if (/^configFor:/m.test(raw)) return;
    const columns = this.parseConfigColumns(raw);
    const frontmatter = this.app.metadataCache.getFileCache(file)?.frontmatter || {};
    const mappings = this.currentMappings();
    const entry = Object.entries(mappings).find(([, mapping]) => mapping.target === file.path);
    const schemaName = typeof frontmatter.implements === "string" ? frontmatter.implements : entry?.[0];
    if (!schemaName || !this.schemaFile(schemaName)) return;
    const fields = this.schemas.get(schemaName) || {};
    const implementationProperties = Object.keys(frontmatter).filter((name) => name !== "implements");
    const tableProperties = columns.length >= 2 ? columns : [];
    const unknown = [...new Set([...implementationProperties, ...tableProperties])].filter((name) => !Object.prototype.hasOwnProperty.call(fields, name));
    if (unknown.length === 0) return;
    if (!window.confirm(`${file.path} added ${unknown.join(", ")}. Define these columns in the ${schemaName} schema?`)) return;
    const nextFields = { ...fields };
    for (const column of unknown) {
      const value = frontmatter[column];
      const type = value === null ? "string" : Array.isArray(value) ? "array" : typeof value === "number" ? "number" : typeof value === "boolean" ? "boolean" : typeof value === "object" ? "object" : "string";
      nextFields[column] = { type, required: false, hasDefault: false, defaultValue: undefined };
    }
    if (!this.schemaFile(schemaName)) return;
    await this.writeSchemaFile(schemaName, nextFields, file.path);
    await this.loadSchemas();
    this.refreshDashboards();
    new Notice(`Added ${unknown.length} field(s) to ${schemaName}.`);
  }

  async addSchemaFieldsToImplementation(schemaName, fields) {
    const source = this.schemaSource(schemaName) || this.currentMappings()[schemaName]?.target;
    if (!source) return;
    const file = this.app.vault.getAbstractFileByPath(source);
    if (!(file instanceof TFile)) return;
    const raw = await this.app.vault.read(file);
    const columns = this.parseConfigColumns(raw);
    if (columns.length < 2) return;
    const missing = Object.keys(fields).filter((field) => !columns.includes(field));
    if (missing.length === 0) return;
    const lines = raw.split(/\r?\n/).map(line => line.trim());
    const tableIndex = lines.findIndex((line) => line.trim().startsWith("|") && line.trim().endsWith("|"));
    const separatorIndex = tableIndex + 1;
    if (tableIndex < 0 || !lines[separatorIndex]) return;
    const addCells = (line) => `${line.trimEnd().slice(0, -1)} ${missing.map((field) => `| ${field} `).join("")}|`;
    lines[tableIndex] = addCells(lines[tableIndex]);
    lines[separatorIndex] = addCells(lines[separatorIndex].replace(/\|\s*$/, "|"));
    await this.app.vault.modify(file, lines.join("\n"));
  }

  parseFieldSpec(spec) {
    const [name, type = "string", ...options] = spec.split(":").map((part) => part.trim());
    if (!name || !FIELD_TYPES.includes(type)) return null;
    const definition = { type, required: options.includes("required"), hasDefault: false, defaultValue: undefined, bind: !options.includes("unbound") };
    const defaultOption = options.find((option) => option !== "required" && option !== "unbound");
    if (defaultOption !== undefined) {
      definition.hasDefault = true;
      if (type === "number") definition.defaultValue = Number(defaultOption);
      else if (type === "boolean") definition.defaultValue = defaultOption === "true";
      else if (type === "array" || type === "object") {
        try { definition.defaultValue = JSON.parse(defaultOption); } catch { definition.defaultValue = defaultOption; }
      } else definition.defaultValue = defaultOption;
    }
    return { name, definition };
  }

  editorValue(value) {
    if (value === undefined) return "";
    if (typeof value === "string") return value;
    return JSON.stringify(value);
  }

  // Moves a renamed key in every record implementing the schema, preserving the
  // value. Without this a rename silently orphans the data: the schema forgets
  // the old key and validation then reports it as undeclared on every note.
  async renameRecordField(schemaName, oldName, newName) {
    for (const file of this.dataFiles()) {
      if (this.app.metadataCache.getFileCache(file)?.frontmatter?.implements !== schemaName) continue;
      await this.app.fileManager.processFrontMatter(file, (current) => {
        if (!(oldName in current) || newName in current) return;
        current[newName] = current[oldName];
        delete current[oldName];
      });
    }
  }

  async saveSchemaFromDashboard(schemaName, editor) {
    const file = this.schemaFile(schemaName);
    if (!file) return;
    const fields = {};
    const renames = [];
    for (const row of editor.querySelectorAll("[data-schema-row]")) {
      const original = row.dataset.schemaRow;
      const input = row.querySelector("[data-field-name]");
      const typed = input?.value.trim() || "";
      // A blank name is a mistake, not an instruction. Restore what was there
      // and abandon the whole save rather than writing a half-renamed schema.
      if (input && !typed) {
        input.value = original;
        new Notice(`A field name cannot be blank. Reverted to "${original}".`);
        return;
      }
      const name = typed || original;
      if (Object.prototype.hasOwnProperty.call(fields, name)) {
        if (input) input.value = original;
        new Notice(`${schemaName} already has a field named "${name}".`);
        return;
      }
      if (name !== original) renames.push([original, name]);
      const rawType = row.querySelector("[data-field-type]")?.value;
      const type = FIELD_TYPES.includes(rawType) ? rawType : "string";
      const required = row.querySelector("[data-field-required]")?.checked === true;
      const bind = row.querySelector("[data-field-bind]")?.value !== "no";
      const relationTarget = row.querySelector("[data-field-relation]")?.value || "";
      const rawDefault = row.querySelector("[data-field-default]")?.value || "";
      const definition = { type, required, bind, hasDefault: rawDefault.length > 0, defaultValue: undefined };
      if (definition.hasDefault) {
        if (type === "number") definition.defaultValue = Number(rawDefault);
        else if (type === "boolean") definition.defaultValue = rawDefault === "true";
        else if (type === "array" || type === "object") {
          try { definition.defaultValue = JSON.parse(rawDefault); } catch { definition.defaultValue = rawDefault; }
        } else definition.defaultValue = rawDefault;
      }
      if (relationTarget) definition.relation = { target: relationTarget };
      fields[name] = definition;
    }
    for (const [oldName, newName] of renames) await this.renameRecordField(schemaName, oldName, newName);
    await this.writeSchemaFile(schemaName, fields);
    await this.addSchemaFieldsToImplementation(schemaName, fields);
    await this.syncEntityFieldsForSchema(schemaName, fields);
    this.schemas.set(schemaName, fields);
    this.refreshDashboards();
    new Notice(renames.length ? `${schemaName} saved; renamed ${renames.map(([o, n]) => `${o} → ${n}`).join(", ")} in records.` : `${schemaName} schema saved.`);
  }

  async deleteSchemaField(schemaName, fieldName) {
    const file = this.schemaFile(schemaName);
    if (!file) return;
    if (!this.skipDeleteConfirm) {
      // Mirrors Obsidian's own "don't ask again" on file deletion, and like it
      // the choice lasts only for this session.
      const answer = await new Promise((resolve) => new ConfirmDeleteModal(this.app, `Remove "${fieldName}"?`, `This removes the field from the ${schemaName} schema. Values already stored in records are left untouched.`, "Remove field", resolve).open());
      if (!answer.confirmed) return;
      if (answer.remember) this.skipDeleteConfirm = true;
    }
    const fields = { ...(this.schemas.get(schemaName) || {}) };
    delete fields[fieldName];
    await this.writeSchemaFile(schemaName, fields);
    await this.loadSchemas();
    this.refreshDashboards();
  }

  async reorderSchemaFields(schemaName, fromName, toName) {
    const fields = this.schemas.get(schemaName);
    if (!fields) return;
    const next = reorderFields(fields, fromName, toName);
    await this.writeSchemaFile(schemaName, next);
    this.schemas.set(schemaName, next);
    await this.syncBaseViews();
    this.refreshDashboards();
  }

  promptSchemaValue(title, placeholder, defaultValue, callback) {
    new SchemaInputModal(this.app, title, placeholder, defaultValue, callback).open();
  }

  async createSchema() {
    this.promptSchemaValue("New schema", "PascalCase schema name", "", async (name) => {
      const schemaName = this.pascalCase(name);
      if (this.schemas.has(schemaName)) return new Notice(`Schema "${schemaName}" already exists.`);
      this.promptSchemaValue("Initial fields", "name:string:required, hp:number:100", "name:string:required", async (spec) => {
        const fields = {};
        for (const item of spec.split(",")) {
          const parsed = this.parseFieldSpec(item.trim());
          if (parsed) fields[parsed.name] = parsed.definition;
        }
        await this.writeNewSchema(schemaName, fields);
      });
    });
  }

  async writeNewSchema(schemaName, fields) {
    await this.ensureFolder(SCHEMA_FOLDER);
    const path = normalizePath(`${SCHEMA_FOLDER}/${schemaName}.schema.md`);
    if (this.app.vault.getAbstractFileByPath(path)) return new Notice(`Schema file already exists: ${path}`);
    try {
      await this.app.vault.create(path, renderSchemaNote(schemaName, fields));
      await this.loadSchemas();
      this.selectedSchema = schemaName;
      this.refreshDashboards();
      new Notice(`Schema "${schemaName}" created.`);
    } catch (error) {
      new Notice(`Could not create schema: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  async duplicateSchema(schemaName) {
    const sourceFields = this.schemas.get(schemaName);
    if (!sourceFields) return;
    this.promptSchemaValue("Duplicate schema", "New PascalCase schema name", `${schemaName}Copy`, async (requestedName) => {
      const targetName = this.pascalCase(requestedName);
      if (this.schemas.has(targetName)) return new Notice(`Schema "${targetName}" already exists.`);
      const fields = Object.fromEntries(Object.entries(sourceFields).map(([name, definition]) => [name, { ...definition, relation: definition.relation ? { ...definition.relation } : undefined }]));
      await this.writeNewSchema(targetName, fields);
      new Notice(`Schema "${targetName}" duplicated from "${schemaName}".`);
    });
  }

  async updateSchema(schemaName) {
    const file = this.schemaFile(schemaName);
    if (!file) return;
    this.promptSchemaValue("Add field", "field:type[:default|:required]", "", async (spec) => {
      const parsed = this.parseFieldSpec(spec);
      if (!parsed) return new Notice("Use string, number, boolean, array, or object as the field type.");
      const fields = { ...(this.schemas.get(schemaName) || {}), [parsed.name]: parsed.definition };
      await this.writeSchemaFile(schemaName, fields);
      await this.addSchemaFieldsToImplementation(schemaName, fields);
      await this.syncEntityFieldsForSchema(schemaName, fields);
      this.schemas.set(schemaName, fields);
      this.refreshDashboards();
      new Notice(`Field "${parsed.name}" added to ${schemaName}.`);
    });
  }

  async deleteSchema(schemaName) {
    const file = this.schemaFile(schemaName);
    if (!file || !window.confirm(`Delete schema "${schemaName}"? Existing entity notes will not be deleted.`)) return;
    await this.app.vault.delete(file);
    await this.loadSchemas();
    this.refreshDashboards();
    new Notice(`Schema "${schemaName}" deleted.`);
  }

  mappingFile() {
    return this.app.vault.getAbstractFileByPath(SCHEMA_MAPPING_FILE) || this.app.vault.getAbstractFileByPath(LEGACY_MAPPING_FILE);
  }

  currentMappings() {
    const file = this.mappingFile();
    return file instanceof TFile ? this.app.metadataCache.getFileCache(file)?.frontmatter?.schemaMappings || {} : {};
  }

  async bindFields(schemaName) {
    const fields = this.schemas.get(schemaName) || {};
    const target = window.prompt("Target config path", "assets/config/Entities.md");
    if (!target?.trim()) return;
    const bindings = {};
    for (const fieldName of Object.keys(fields)) {
      const value = window.prompt(`Target attribute for ${fieldName}`, fieldName);
      if (value?.trim()) bindings[fieldName] = value.trim();
    }
    const mappings = { ...this.currentMappings(), [schemaName]: { target: target.trim(), fields: bindings } };
    await this.saveMappings(mappings);
    this.refreshDashboards();
    new Notice(`Bindings saved for ${schemaName}.`);
  }

  async unbindFields(schemaName) {
    const mappings = { ...this.currentMappings() };
    if (!mappings[schemaName]) return new Notice(`No bindings found for ${schemaName}.`);
    delete mappings[schemaName];
    await this.saveMappings(mappings);
    this.refreshDashboards();
    new Notice(`Bindings removed for ${schemaName}.`);
  }

  // Single writer for the mappings note. Previously three near-identical copies
  // of this existed, and all of them created the folder "config" while writing
  // to data/config/schema-mappings.md.
  async writeMappingsFile(schemaMappings, records, generatedPaths) {
    await this.ensureFolder(CONFIG_FOLDER);
    const content = `---\nschemaMappings: ${JSON.stringify(schemaMappings)}\nrecordMappings: ${JSON.stringify(records)}\ngeneratedPaths: ${JSON.stringify(generatedPaths)}\n---\n\n# Schema Mappings\n\nField bindings are tracked by vault path, not note name.\n`;
    const file = this.mappingFile();
    if (!(file instanceof TFile)) return this.app.vault.create(SCHEMA_MAPPING_FILE, content);
    // Compare before writing: syncSystem calls this on every run, and a
    // no-op write still churns the file's mtime and Obsidian Sync.
    if (await this.app.vault.read(file) !== content) await this.app.vault.modify(file, content);
    return file;
  }

  async saveMappings(mappings) {
    await this.writeMappingsFile(mappings, this.currentRecordMappings(), this.currentGeneratedPaths());
  }

  async saveGeneratedPaths(generatedPaths) {
    await this.writeMappingsFile(this.currentMappings(), this.currentRecordMappings(), generatedPaths);
  }

  currentRecordMappings() {
    const file = this.mappingFile();
    return file instanceof TFile ? this.app.metadataCache.getFileCache(file)?.frontmatter?.recordMappings || {} : {};
  }

  currentGeneratedPaths() {
    const file = this.mappingFile();
    return file instanceof TFile ? this.app.metadataCache.getFileCache(file)?.frontmatter?.generatedPaths || {} : {};
  }

  async trackRecord(filePath, schemaName) {
    const records = { ...this.currentRecordMappings(), [filePath]: { schema: schemaName } };
    await this.saveRecordMappings(records);
  }

  async saveRecordMappings(records) {
    await this.writeMappingsFile(this.currentMappings(), records, this.currentGeneratedPaths());
  }

  async updateTrackedPath(oldPath, newPath) {
    const schemaMappings = { ...this.currentMappings() };
    let changed = false;
    for (const mapping of Object.values(schemaMappings)) {
      if (mapping.target === oldPath) {
        mapping.target = newPath;
        changed = true;
      }
    }
    const records = { ...this.currentRecordMappings() };
    if (records[oldPath]) {
      records[newPath] = records[oldPath];
      delete records[oldPath];
      changed = true;
    }
    const generatedPaths = { ...this.currentGeneratedPaths() };
    if (generatedPaths[oldPath]) {
      generatedPaths[newPath] = generatedPaths[oldPath];
      delete generatedPaths[oldPath];
      changed = true;
    }
    if (changed) await this.writeMappingsFile(schemaMappings, records, generatedPaths);
  }

  async handleTrackedRename(oldPath, newPath) {
    await this.updateTrackedPath(oldPath, newPath);
    const sourceSchemas = this.app.vault.getMarkdownFiles().filter((file) => {
      const frontmatter = this.app.metadataCache.getFileCache(file)?.frontmatter;
      return this.isSchemaPath(file.path) && frontmatter?.schemaSource === oldPath;
    });
    for (const schemaFile of sourceSchemas) {
      await this.app.fileManager.processFrontMatter(schemaFile, (frontmatter) => {
        frontmatter.schemaSource = newPath;
      });
    }
    this.refreshDashboards();
    const movedConfig = newPath.startsWith(`${CONFIG_FOLDER}/`) || newPath.startsWith(`${ASSET_CONFIG_FOLDER}/`);
    if (movedConfig) {
      const movedFile = this.app.vault.getAbstractFileByPath(newPath);
      if (movedFile instanceof TFile) void this.checkImplementationColumns(movedFile);
    }
  }

  // Creates a real record in the schema's own records folder, carrying every
  // field. Repeatable: each press takes the next free number, starting at 2 so
  // the numbering sits alongside the unnumbered _placeholder template.
  async implementEntity(schemaName) {
    const fields = this.schemas.get(schemaName);
    if (!fields) return new Notice(`Schema "${schemaName}" was not found.`);
    const folder = await this.folderForSchema(schemaName);
    await this.ensureFolder(folder);
    const stem = PLACEHOLDER_PREFIX.slice(0, -1);
    let index = 2;
    let path = normalizePath(`${folder}/${stem}${index}.${schemaName}.md`);
    while (this.app.vault.getAbstractFileByPath(path)) {
      index += 1;
      path = normalizePath(`${folder}/${stem}${index}.${schemaName}.md`);
    }
    await this.app.vault.create(path, `---\n${renderRecordFrontmatter(schemaName, fields)}\n---\n# ${schemaName} ${index}\n\nRecord generated from the ${schemaName} schema. Rename this note once it holds real data.\n`);
    await this.trackRecord(path, schemaName);
    this.refreshDashboards();
    new Notice(`Created ${path}.`);
  }

  async forgetRecord(recordPath) {
    const records = this.currentRecordMappings();
    if (!records[recordPath]) return;
    const next = { ...records };
    delete next[recordPath];
    await this.saveRecordMappings(next);
  }

  async deleteRecord(recordPath) {
    const file = this.app.vault.getAbstractFileByPath(recordPath);
    if (!(file instanceof TFile)) return new Notice("That record no longer exists.");
    if (!this.skipRecordDeleteConfirm) {
      const answer = await new Promise((resolve) => new ConfirmDeleteModal(this.app, `Delete "${file.basename}"?`, `${file.path} will be moved to trash.`, "Delete record", resolve).open());
      if (!answer.confirmed) return;
      if (answer.remember) this.skipRecordDeleteConfirm = true;
    }
    // trashFile honours the vault's own "move to system trash" setting rather
    // than deleting outright.
    if (this.app.fileManager.trashFile) await this.app.fileManager.trashFile(file);
    else await this.app.vault.trash(file, true);
    await this.forgetRecord(recordPath);
    this.refreshDashboards();
    new Notice(`Deleted ${file.basename}.`);
  }

  async duplicateRecord(recordPath) {
    const source = this.app.vault.getAbstractFileByPath(recordPath);
    if (!(source instanceof TFile)) return new Notice("That record no longer exists.");
    const raw = await this.app.vault.read(source);
    const folder = source.parent?.path && source.parent.path !== "/" ? source.parent.path : DATA_FOLDER;
    let index = 2;
    let path = normalizePath(`${folder}/${source.basename} ${index}.md`);
    while (this.app.vault.getAbstractFileByPath(path)) {
      index += 1;
      path = normalizePath(`${folder}/${source.basename} ${index}.md`);
    }
    const created = await this.app.vault.create(path, raw);
    const schemaName = this.app.metadataCache.getFileCache(source)?.frontmatter?.implements;
    if (typeof schemaName === "string") await this.trackRecord(path, schemaName);
    this.refreshDashboards();
    await this.app.workspace.getLeaf(true).openFile(created);
    new Notice(`Duplicated to ${path}.`);
  }

  // Asset Renamer builds its property picker from the note's frontmatter keys,
  // so an attachment-typed field is selectable there with no changes on its side.
  async openAssetRenamer(recordPath) {
    const file = this.app.vault.getAbstractFileByPath(recordPath);
    if (!(file instanceof TFile)) return new Notice("That record no longer exists.");
    await this.app.workspace.getLeaf(true).openFile(file);
    const command = this.app.commands?.commands?.["asset-renamer:open-asset-renamer"];
    if (!command) return new Notice("Asset Renamer is not enabled.");
    this.app.commands.executeCommandById("asset-renamer:open-asset-renamer");
  }

  onunload() {
    for (const timeout of this.pending.values()) clearTimeout(timeout);
    this.pending.clear();
    if (this.schemaValidationTimeout) clearTimeout(this.schemaValidationTimeout);
    if (this.schemaReloadTimeout) clearTimeout(this.schemaReloadTimeout);
    if (this.schemaPreviewTimeout) clearTimeout(this.schemaPreviewTimeout);
  }

  scheduleSchemaValidation() {
    if (this.schemaValidationTimeout) clearTimeout(this.schemaValidationTimeout);
    this.schemaValidationTimeout = setTimeout(() => {
      this.schemaValidationTimeout = null;
      void this.syncSystem(false);
    }, 250);
  }

  scheduleValidation(file) {
    if (!(file instanceof TFile) || !this.isRecordFile(file)) return;
    const previous = this.pending.get(file.path);
    if (previous) clearTimeout(previous);
    this.pending.set(
      file.path,
      setTimeout(() => {
        this.pending.delete(file.path);
        void this.validateFile(file, true);
      }, 250)
    );
  }

  async validateVault(showSummary) {
    await this.loadSchemas();
    const files = this.dataFiles();
    let issues = 0;
    for (const file of files) issues += await this.validateFile(file, false);
    this.statusBar.setText(issues ? `Schema Sync: ${issues} issue(s)` : "Schema Sync: OK");
    if (showSummary) {
      new Notice(issues ? `Schema Sync found ${issues} issue(s).` : "Schema Sync: all notes are valid.");
    }
  }

  async syncSystem(showNotice) {
    await this.loadSchemas();
    for (const [schemaName, fields] of this.schemas) {
      await this.syncEntityFieldsForSchema(schemaName, fields);
    }
    await this.ensurePlaceholders();
    await this.importLists();
    // Config lists read record values, so they must run after records are
    // back-filled. Base views depend only on schema fields.
    await this.syncConfigLists();
    const generated = {};
    await this.syncBaseViews(generated);
    await this.cleanupGeneratedPaths(generated);
    await this.saveGeneratedPaths(generated);
    await this.syncSchemaDocs();
    await this.validateVault(showNotice);
    this.refreshDashboards();
  }

  async syncEntityFieldsForSchema(schemaName, fields) {
    const entities = this.dataFiles().filter((file) => !file.basename.startsWith(PLACEHOLDER_PREFIX));
    for (const file of entities) {
      const frontmatter = this.app.metadataCache.getFileCache(file)?.frontmatter;
      if (frontmatter?.implements !== schemaName) continue;
      await this.app.fileManager.processFrontMatter(file, (current) => {
        for (const [fieldName, definition] of Object.entries(fields)) {
          if (!isBound(definition) || fieldName in current) continue;
          current[fieldName] = definition.hasDefault ? definition.defaultValue : emptyValue(definition.type);
        }
      });
    }
  }

  // `.base` is Obsidian Bases YAML; `.base.md` is a note wrapping a DBML fence
  // for the DBML Visualizer plugin. Two unrelated formats — writing DBML into a
  // `.base` file is what made Bases report "unable to parse file".
  async syncBaseViews(generated = {}) {
    if (this.schemas.size === 0) return;
    await this.ensureFolder(BASE_VIEW_FOLDER);
    for (const [schemaName, fields] of this.schemas) {
      const folder = await this.folderForSchema(schemaName);
      const path = normalizePath(`${BASE_VIEW_FOLDER}/${schemaName}.base`);
      await this.writeFile(path, renderBaseYaml(schemaName, fields, folder));
      generated[path] = schemaName;
    }
    await this.syncErd(generated);
  }

  async syncErd(generated = {}) {
    const path = normalizePath(`${BASE_FOLDER}/${this.databaseName()}.base.md`);
    await this.writeFile(path, renderErdNote(this.databaseName(), this.schemas));
    generated[path] = "*";
  }

  // Only paths this plugin recorded as generated are ever deleted. The previous
  // implementation cleared every .base / .base.md under data/, taking
  // hand-authored files with it.
  async cleanupGeneratedPaths(generated) {
    for (const path of Object.keys(this.currentGeneratedPaths())) {
      if (Object.prototype.hasOwnProperty.call(generated, path)) continue;
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof TFile) await this.app.vault.delete(file);
    }
  }

  // One .config.md per attribute name, shared across every schema declaring it.
  // Values found in records are unioned with whatever the file already holds, so
  // hand-added options are never dropped. These are deliberately not registered
  // as generated paths: they carry user-curated content and must survive a field
  // being renamed or removed.
  async syncConfigLists() {
    const attributes = new Map();
    for (const [schemaName, fields] of this.schemas) {
      for (const [fieldName, definition] of Object.entries(fields)) {
        // Attachments hold media links, not categories, so they get no list.
        if (definition.type !== "string" || definition.relation?.target || !isBound(definition)) continue;
        // `id` and `name` are identity keys, not category enums — the same two
        // names dbmlRefTarget() treats as a table's key. A list of every id in
        // the vault is noise, not a dropdown.
        if (IDENTITY_FIELDS.has(fieldName.toLowerCase())) continue;
        if (!attributes.has(fieldName)) attributes.set(fieldName, { sources: [], values: new Set() });
        attributes.get(fieldName).sources.push(`${schemaName}.${fieldName}`);
      }
    }
    if (attributes.size === 0) return;
    await this.ensureFolder(CONFIG_FOLDER);
    for (const file of this.dataFiles()) {
      if (file.basename.startsWith(PLACEHOLDER_PREFIX)) continue;
      const frontmatter = this.app.metadataCache.getFileCache(file)?.frontmatter;
      if (!frontmatter || typeof frontmatter.implements !== "string") continue;
      const fields = this.schemas.get(frontmatter.implements);
      if (!fields) continue;
      for (const fieldName of Object.keys(fields)) {
        const entry = attributes.get(fieldName);
        if (!entry) continue;
        const raw = frontmatter[fieldName];
        for (const value of Array.isArray(raw) ? raw : [raw]) {
          const text = typeof value === "string" ? value.trim().replace(/^\[\[|\]\]$/g, "").trim() : "";
          if (text) entry.values.add(text);
        }
      }
    }
    for (const [fieldName, entry] of attributes) {
      const path = normalizePath(`${CONFIG_FOLDER}/${pluralize(fieldName)}.config.md`);
      const existing = this.app.vault.getAbstractFileByPath(path);
      const existingValues = existing instanceof TFile ? parseConfigValues(await this.app.vault.read(existing)) : [];
      await this.writeFile(path, renderConfigNote(fieldName, entry.sources, [...entry.values], existingValues));
    }
  }

  dataFiles() {
    return this.app.vault.getMarkdownFiles().filter((file) => this.isRecordFile(file));
  }

  isRecordFile(file) {
    if (file.path === "config/entity.md") return true;
    if (!file.path.startsWith("data/")) return false;
    return !file.path.startsWith(`${SCHEMA_FOLDER}/`) && !file.path.startsWith(`${CONFIG_FOLDER}/`) && !file.path.startsWith(`${TABLE_FOLDER}/`) && !file.path.endsWith(".base.md") && file.extension === "md";
  }

  async ensureFolder(path) {
    const normalized = normalizePath(path);
    if (!this.app.vault.getAbstractFileByPath(normalized)) {
      await this.app.vault.createFolder(normalized);
    }
  }

  async folderForSchema(schemaName) {
    const counts = new Map();
    for (const file of this.dataFiles()) {
      if (file.basename.startsWith(PLACEHOLDER_PREFIX)) continue;
      const frontmatter = this.app.metadataCache.getFileCache(file)?.frontmatter;
      if (frontmatter?.implements !== schemaName) continue;
      const folder = file.path.slice(0, file.path.lastIndexOf("/"));
      counts.set(folder, (counts.get(folder) || 0) + 1);
    }
    let winner = "";
    let max = 0;
    for (const [folder, count] of counts) {
      if (count > max) {
        winner = folder;
        max = count;
      }
    }
    return winner || `${DATA_FOLDER}/${schemaName.toLowerCase()}s`;
  }

  // Every field, not just required and defaulted ones. Records and placeholders
  // must carry the whole schema so the columns exist to be filled in.
  recordValuesFor(schemaName, fields) {
    return recordValuesFor(schemaName, fields);
  }

  emptyValue(type) {
    return emptyValue(type);
  }

  yamlValue(value) {
    return yamlValue(value);
  }

  frontmatterText(values) {
    return frontmatterText(values);
  }

  // Back-fills an existing placeholder rather than skipping it, so fields added
  // to a schema after the placeholder was created still appear. Values already
  // present are left alone.
  async ensurePlaceholders() {
    for (const [schemaName, fields] of this.schemas) {
      const folder = await this.folderForSchema(schemaName);
      await this.ensureFolder(folder);
      const path = normalizePath(`${folder}/${PLACEHOLDER_PREFIX}${schemaName}.md`);
      const existing = this.app.vault.getAbstractFileByPath(path);
      if (existing instanceof TFile) {
        await this.app.fileManager.processFrontMatter(existing, (current) => {
          current.implements = schemaName;
          for (const [name, definition] of Object.entries(fields)) {
            if (name in current) continue;
            current[name] = definition.hasDefault ? definition.defaultValue : emptyValue(definition.type);
          }
        });
        continue;
      }
      await this.app.vault.create(path, `---\n${renderRecordFrontmatter(schemaName, fields)}\n---\n# ${schemaName} Placeholder\n\nUse this file as a template and duplicate it when creating new ${schemaName} notes.\n`);
    }
  }

  async importLists() {
    const listFiles = this.app.vault.getFiles().filter((file) =>
      file.path.startsWith(`${LIST_FOLDER}/`) && file.extension.toLowerCase() === "csv"
    );
    for (const listFile of listFiles) {
      const schemaName = listFile.basename;
      const fields = this.schemas.get(schemaName);
      if (!fields) continue;
      const folder = await this.folderForSchema(schemaName);
      await this.ensureFolder(folder);
      const raw = await this.app.vault.read(listFile);
      const names = [...new Set(raw.replace(/^\uFEFF/, "").split(/\r?\n/).map((line) => line.split(",")[0].trim().replace(/^"(.*)"$/, "$1")).filter((name) => name && !/^name$/i.test(name)))];
      const labelField = fields.name ? "name" : Object.keys(fields).find((name) => fields[name].required && fields[name].type === "string") || Object.keys(fields)[0];
      for (const name of names) {
        const safeName = name.replace(/[<>:"/\\|?*\x00-\x1F]/g, "_").replace(/[. ]+$/g, "") || "Untitled";
        const path = normalizePath(`${folder}/${safeName}.md`);
        if (this.app.vault.getAbstractFileByPath(path)) continue;
        const values = recordValuesFor(schemaName, fields);
        if (labelField) values[labelField] = name;
        await this.app.vault.create(path, `---\n${frontmatterText(values)}\n---\n# ${name}\n\nAuto-generated from ${schemaName}.csv list import.\n`);
      }
    }
  }

  // Rewrites each schema note so its `schema:` property, title heading and
  // Field Reference all agree with its filename. Idempotent: a second pass over
  // a repaired file produces identical text and writes nothing.
  async syncSchemaDocs() {
    for (const [schemaName, fields] of this.schemas) {
      const file = this.schemaFile(schemaName);
      if (!file) continue;
      // Never rewrite the note the user is looking at, whatever triggered this
      // sync. Their edits already reached the registry through loadSchemas();
      // writing back over them is what made direct editing feel broken.
      if (this.safetyOff.has(file.path) || this.app.workspace.getActiveFile()?.path === file.path) continue;
      const frontmatter = this.app.metadataCache.getFileCache(file)?.frontmatter;
      const raw = await this.app.vault.read(file);
      // A note whose declared name disagrees with its filename has prose about
      // the wrong entity, so it is reset rather than carried over.
      const body = frontmatter?.schema === schemaName ? schemaBodyOf(raw) : undefined;
      const next = renderSchemaNote(schemaName, fields, frontmatter?.schemaSource, body);
      if (next !== raw) await this.app.vault.modify(file, next);
    }
  }

  async syncTables() {
    await this.ensureFolder(TABLE_FOLDER);
    for (const [schemaName, fields] of this.schemas) {
      const fieldNames = Object.keys(fields);
      const rows = this.dataFiles().filter((file) => !file.basename.startsWith(PLACEHOLDER_PREFIX)).map((file) => ({ file, frontmatter: this.app.metadataCache.getFileCache(file)?.frontmatter })).filter((item) => item.frontmatter?.implements === schemaName);
      const header = ["note", "implements", ...fieldNames];
      const line = (values) => `| ${values.map((value) => String(value ?? "").replace(/\|/g, "\\|")).join(" | ")} |`;
      const content = `# ${schemaName} Table DB\n\nAuto-generated mapping table for notes implementing \`${schemaName}\`. Paths are identities; note names may repeat.\n\n${line(header)}\n${line(header.map(() => "---"))}\n${rows.length ? rows.map(({ file, frontmatter }) => line([file.path, schemaName, ...fieldNames.map((name) => this.yamlValue(frontmatter[name]))])).join("\n") : line(["_none_", schemaName, ...fieldNames.map(() => "")])}\n`;
      const path = normalizePath(`${TABLE_FOLDER}/${schemaName}.table.md`);
      const existing = this.app.vault.getAbstractFileByPath(path);
      if (existing instanceof TFile) await this.app.vault.modify(existing, content);
      else await this.app.vault.create(path, content);
    }
  }

  async loadSchemas() {
    this.schemas.clear();
    for (const file of this.app.vault.getMarkdownFiles()) {
      if (!this.isSchemaPath(file.path)) continue;
      const key = this.schemaKeyFor(file);
      if (typeof key !== "string" || !key) continue;
      const frontmatter = this.app.metadataCache.getFileCache(file)?.frontmatter;
      this.schemas.set(key, this.readFields(frontmatter?.fields));
    }
  }

  readFields(rawFields) {
    const fields = {};
    const entries = Array.isArray(rawFields)
      ? rawFields
      : rawFields && typeof rawFields === "object"
        ? Object.entries(rawFields).map(([name, meta]) => ({ [name]: meta }))
        : [];
    for (const entry of entries) {
      if (!entry || typeof entry !== "object") continue;
      for (const [name, rawDefinition] of Object.entries(entry)) {
        if (!rawDefinition || typeof rawDefinition !== "object") continue;
        const definition = rawDefinition;
        fields[name] = {
          type: FIELD_TYPES.includes(definition.type) ? definition.type : "string",
          required: definition.required === true,
          hasDefault: Object.prototype.hasOwnProperty.call(definition, "default"),
          defaultValue: definition.default,
          relation: typeof definition.relation === "string" ? { target: definition.relation } : definition.relation,
          // Absent means bound. Only an explicit `bind: false` unbinds a field.
          bind: definition.bind !== false,
        };
      }
    }
    return fields;
  }

  async validateFile(file, showNotice) {
    if (file.basename.startsWith(PLACEHOLDER_PREFIX)) return 0;
    const frontmatter = this.app.metadataCache.getFileCache(file)?.frontmatter;
    if (!frontmatter || typeof frontmatter.implements !== "string") return 0;

    if (this.schemas.size === 0) await this.loadSchemas();
    const fields = this.schemas.get(frontmatter.implements);
    if (!fields) {
      if (showNotice) new Notice(`${file.path}: schema "${frontmatter.implements}" was not found.`);
      return 1;
    }

    const errors = [];
    const defaults = {};
    for (const [name, definition] of Object.entries(fields)) {
      // Unbound fields are never written to records, so they are never missing.
      if (!isBound(definition)) continue;
      if (!(name in frontmatter) || frontmatter[name] === null || frontmatter[name] === undefined) {
        if (definition.hasDefault) defaults[name] = definition.defaultValue;
        else if (definition.required) errors.push(`${name} is required`);
        continue;
      }
      const actual = this.valueType(frontmatter[name]);
      // An attachment is stored as a string holding a [[wikilink]].
      if (actual !== storageType(definition.type)) {
        errors.push(`${name} expects ${definition.type}, got ${actual}`);
        continue;
      }
      // Records now carry every field, so a required field arrives present but
      // blank. Without this the whole vault would validate clean.
      if (definition.required && isEmptyValue(frontmatter[name])) errors.push(`${name} is required`);
    }

    for (const name of Object.keys(frontmatter)) {
      if (name !== "implements" && !Object.prototype.hasOwnProperty.call(fields, name)) {
        errors.push(`${name} is not declared by schema ${frontmatter.implements}`);
      }
    }

    if (Object.keys(defaults).length > 0 && !this.patching.has(file.path)) {
      this.patching.add(file.path);
      try {
        await this.app.fileManager.processFrontMatter(file, (current) => {
          for (const [name, value] of Object.entries(defaults)) {
            if (!(name in current) || current[name] === null || current[name] === undefined) current[name] = value;
          }
        });
      } finally {
        this.patching.delete(file.path);
      }
    }

    if (showNotice && errors.length > 0) {
      new Notice(`${file.path}: ${errors.join("; ")}`, 10000);
    }
    return errors.length;
  }

  valueType(value) {
    if (Array.isArray(value)) return "array";
    if (value === null) return "null";
    return typeof value;
  }
}

module.exports = SchemaSyncPlugin;

// Exposed for the out-of-vault test script. Obsidian ignores extra exports.
module.exports.generators = {
  emptyValue,
  isEmptyValue,
  isBound,
  storageType,
  reorderFields,
  renameField,
  yamlValue,
  frontmatterText,
  pluralize,
  recordValuesFor,
  renderRecordFrontmatter,
  renderBaseYaml,
  parseConfigValues,
  renderConfigNote,
  renderFieldReference,
  schemaBodyOf,
  renderSchemaNote,
  renderDbml,
  renderErdNote,
};